### ISSUE TITLE
Check that lib is `no_std` in CI

### ISSUE THREAD

**Issue by survived** [dfns/stark-curve#6]
Library does have `#![no_std]` flag, but it doesn't mean it's actually no_std friendly as it could have dependencies that aren't `no_std`. 

We should check in CI that lib is actually `no_std` friendly, e.g. by compiling it to musl target.

**Comment by maurges** [comment]
We can be a bit lazy and only have this check in generic-ec or even cggmp instead of putting it to three repos.

I think it's not a musl target, but rather amd64-unknown-unknown or something

**Comment by survived** [comment]
Yeah you're right. Actually, https://github.com/dfns/generic-ec/pull/17 adds the test that project compiles into `wasm32-unknown-unknown`, I think that should be enough
